const labels: Record<string, string> = {
  "auth.login": "Signed in",
  "auth.totp.enabled": "Enabled two-factor authentication",
  "auth.totp.disabled": "Disabled two-factor authentication",
  "password.reset.requested": "Requested password reset",
  "password.reset.completed": "Reset password",
  "item.create": "Item created",
  "item.update": "Item updated",
  "item.delete": "Item deleted",
  "stock.in": "Stock in",
  "stock.out": "Stock out",
  "stock.transfer": "Stock transferred",
  "stock.distribute": "Stock distributed",
  "transfer.request": "Transfer requested",
  "transfer.approve": "Transfer approved",
  "transfer.reject": "Transfer rejected",
  "transfer.cancel": "Transfer cancelled",
  "sale.create": "Sale recorded",
  "shop.create": "Shop created",
  "shop.delete": "Shop deleted",
  "attendant.create": "Attendant created",
  "attendant.reassign": "Attendant reassigned",
  "attendant.deactivate": "Attendant deactivated",
  "attendant.reactivate": "Attendant reactivated",
  "attendant.delete": "Attendant deleted",
  "report.lowStockAlert": "Low stock alert sent",
  "purchaseOrder.create": "Purchase order created",
  "purchaseOrder.receive": "Purchase order received",
  "purchaseOrder.cancel": "Purchase order cancelled",
  "supplier.create": "Supplier added",
  "supplier.delete": "Supplier deleted",
  "workOrder.create": "Work order created",
  "workOrder.part": "Part added to work order",
  "workOrder.status": "Work order status updated",
  "sale.refund": "Sale refunded",
};

const tones: Record<string, "default" | "success" | "warning" | "danger" | "info" | "neutral"> = {
  "auth.login": "neutral",
  "auth.totp.enabled": "neutral",
  "auth.totp.disabled": "neutral",
  "password.reset.requested": "neutral",
  "password.reset.completed": "neutral",
  "item.create": "success",
  "item.update": "info",
  "item.delete": "danger",
  "stock.in": "success",
  "stock.out": "warning",
  "stock.transfer": "info",
  "stock.distribute": "success",
  "transfer.request": "info",
  "transfer.approve": "success",
  "transfer.reject": "danger",
  "transfer.cancel": "neutral",
  "sale.create": "info",
  "shop.create": "success",
  "shop.delete": "danger",
  "attendant.create": "success",
  "attendant.reassign": "info",
  "attendant.deactivate": "danger",
  "attendant.reactivate": "success",
  "attendant.delete": "danger",
  "report.lowStockAlert": "warning",
  "purchaseOrder.create": "success",
  "purchaseOrder.receive": "success",
  "purchaseOrder.cancel": "danger",
  "supplier.create": "success",
  "supplier.delete": "danger",
  "workOrder.create": "success",
  "workOrder.part": "info",
  "workOrder.status": "info",
  "sale.refund": "danger",
};

export function actionLabel(action: string): string {
  return labels[action] ?? action.replaceAll(".", " ");
}

export function actionTone(action: string): "default" | "success" | "warning" | "danger" | "info" | "neutral" {
  return tones[action] ?? "neutral";
}
